SuperDealzApp/urls.py
from django.conf.urls import url, include
from .views import *
from . import views
from django.contrib.auth.views import (
    login, logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

app_name = 'superdealzapp'

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    #URLs Account
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^registro/$', views.register, name='register'),
    url(r'^mi-perfil/$', views.view_profile, name='view_profile'),
    url(r'^mi-perfil/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^cambiar-pass/$', views.change_password, name='change_password'),

    url(r'^reset-pass/$', password_reset,  name='reset_password'),
    url(r'^reset-pass/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-pass/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-pass/complete/$', password_reset_complete,
        {'template_name': 'accounts/reset_password_complete.html'},
        name='password_reset_complete'),

    url(r'^productos$', views.pagina_productos, name="productos"),
    url(r'^comparar_productos$', views.comparar_precios),
    url(r'^acerca_nosotros$', views.acerca_nosotros),
    url(r'^mis-listas$', views.mis_listas),
    # url(r'^destacados$', views.destacados),
    # url(r'^notificaciones$', views.notificaciones),)
    url(r'^error$', views.error),
    url(r'^contacto$', views.contacto),
    # url(r'^cuenta$', views.mi_cuenta),
]

SuperDealzWeb/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('superdealzapp.urls', namespace='superdealz')),
    path('admin/', admin.site.urls),
    path('bootstrap3/',
         TemplateView.as_view(template_name='bootstrap3/inicio.html')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<id_producto>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<id_producto>\d+)/$', views.cart_remove, name='cart_remove'),
]

SuperDealzApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Categoria(models.Model):

    id_categoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=200)

    class Meta:
        db_table = 'categoria'

    def __str__(self):
        return self.nombre


class Producto(models.Model):

    id_producto = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=50)
    nombre = models.TextField()
    descripcion = models.TextField(blank=True)
    medida = models.CharField(max_length=50)
    imagen = models.ImageField(
        upload_to='productos', blank=True, max_length=200)
    url = models.URLField(max_length=500, blank=True)
    disponible = models.BooleanField(default=True)
    categoria = models.ForeignKey(
        Categoria, db_column='id_categoria', on_delete=models.CASCADE)

    class Meta:
        db_table = 'producto'

    def __str__(self):
        return self.nombre


class Error(models.Model):

    id_error = models.AutoField(primary_key=True)
    fecha = models.DateTimeField()
    comentarios = models.CharField(max_length=150)
    url = models.URLField(max_length=100)
    producto = models.ForeignKey(
        Producto, db_column='id_producto', on_delete=models.CASCADE)

    class Meta:
        # managed = False
        db_table = 'error'


class Supermercado(models.Model):
    id_super = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    main_url = models.URLField(max_length=100)
    term_uso = models.URLField(max_length=150)
    logo = models.CharField(max_length=250)
    estado = models.IntegerField()

    class Meta:
        # managed = False
        db_table = 'supermercado'


class Precio(models.Model):
    id_precio = models.AutoField(primary_key=True)
    precio = models.IntegerField()
    creado = models.DateTimeField(auto_now_add=True)
    producto = models.ForeignKey(
        Producto, db_column='id_producto', on_delete=models.CASCADE)
    supermercado = models.ForeignKey(
        Supermercado, db_column='id_super', on_delete=models.CASCADE)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        # managed = False
        db_table = 'precio'

    def __str__(self):
        return self.precio


class Listasuper(models.Model):
    id_listasuper = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        # managed = False
        db_table = 'listasuper'


class Prodxlista(models.Model):
    id_prodxlista = models.AutoField(primary_key=True)
    cantidad = models.IntegerField()
    producto = models.ForeignKey(
        Producto, db_column='id_producto', on_delete=models.CASCADE)
    precio = models.ForeignKey(
        Precio, db_column='id_precio', on_delete=models.CASCADE)
    listasuper = models.ForeignKey(
        Listasuper, db_column='id_listasuper', on_delete=models.CASCADE)

    class Meta:
        # managed = False
        db_table = 'prodxlista'

    def __str__(self):
        return "{} - {}".format(
            self.producto.nombre, self.listasuper.id_usuario.username
        )


class Region(models.Model):
    id_region = models.AutoField(primary_key=True)
    nombre_region = models.CharField(max_length=50)

    class Meta:
        # managed = False
        db_table = 'region'


class Comuna(models.Model):
    id_comuna = models.AutoField(primary_key=True)
    nombre_comuna = models.CharField(max_length=50)
    region = models.ForeignKey(
        Region, db_column='id_region', on_delete=models.CASCADE)

    class Meta:
        # managed = False
        db_table = 'comuna'


class Sucursal(models.Model):

    id_sucursal = models.AutoField(primary_key=True)
    direccion = models.CharField(max_length=50)
    latitud = models.CharField(max_length=50)
    longitud = models.CharField(max_length=50)
    comuna = models.ForeignKey(
        Comuna, db_column='id_comuna', on_delete=models.CASCADE)
    supermercado = models.ForeignKey(
        Supermercado, db_column='id_super', on_delete=models.CASCADE)

    class Meta:
        # managed = False
        db_table = 'sucursal'

SuperDealzApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from haystack.forms import SearchForm


class RegistrationForm(UserCreationForm):

    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):

    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )


class CustomSearchForm(SearchForm):
    # precio = forms.IntegerField(required=False)
    fecha = forms.DateField(required=False)

    def search(self):
        sqs = super(CustomSearchForm, self).search()

        if not self.is_valid():
            return self.no_query_found()

        return sqs

SuperDealzApp/views.py
from django.shortcuts import render, redirect
from django.db.models import Q  # , Prefetch
from django.contrib import messages
from django.utils.translation import gettext as _
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
from django.urls import reverse
from django.contrib.auth import (
    update_session_auth_hash, login, authenticate
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    PasswordChangeForm
)
# from cart.forms import CartAddProductForm
# from fuzzywuzzy import fuzz, process
# from haystack.generic_views import SearchView
from .forms import (
    RegistrationForm, EditProfileForm
)
from .models import (
    Producto, Prodxlista, Precio
)


def inicio(request):

    lista_productos = Producto.objects.all()[:3]

    context = {
        'lista_productos': lista_productos
    }

    return render(request, 'bootstrap3/inicio.html', context)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(view_profile)
    else:
        form = RegistrationForm()

    return render(request, 'accounts/register.html', {'form': form})


@login_required
def view_profile(request):
    listas = Prodxlista.objects.all()

    form = EditProfileForm(data=request.POST or None, instance=request.user)

    if request.POST and form.is_valid():
        form.save()
        return redirect('superdealz:view_profile')

    context = {
        'form': form,
        'listas': listas
    }

    return render(request, 'accounts/my_profile.html', context)


@login_required
def change_password(request):
    listas = Prodxlista.objects.all()

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(
                request, _('Su contraseña fue actualizada con éxito!'))
            return redirect(reverse(view_profile))
        else:
            messages.error(request, _('Por favor corriga los errores.'))
            return redirect(reverse(change_password))
    else:
        form = PasswordChangeForm(user=request.user)

    context = {
        'form': form,
        'listas': listas
    }

    return render(request, 'accounts/change_password.html', context)


def pagina_productos(request):

    list_precios = Precio.objects.\
        select_related('producto', 'supermercado').\
        all()

    search = request.GET.get('q', '')

    if search:
        list_precios = list_precios.\
            filter(
                Q(producto__nombre__icontains=search) |
                Q(producto__marca__icontains=search) |
                Q(producto__categoria__nombre__icontains=search),
            )

    page = request.GET.get('page', 1)
    paginator = Paginator(list_precios, 6)

    try:
        precios = paginator.page(page)
    except PageNotAnInteger:
        precios = paginator.page(1)
    except EmptyPage:
        precios = paginator.page(paginator.num_pages)

    context = {
        'precios': precios,
        'search': search,
    }

    return render(request, 'bootstrap3/pagina_productos.html', context)


def comparar_precios(request):

    comparar = Prodxlista.objects.all()

    for item in comparar:
        matching_results = Producto.objects.\
            filter(
                Q(producto__nombre__icontains=item.producto.nombre) |
                Q(producto__marca__icontains=item.producto.marca)
            )

    context = {
        'comparar': comparar,
        # 'lowest_price': lowest_price,
        # 'lowest_super': lowest_super,
        'matching_results': matching_results
    }

    return render(request, 'bootstrap3/comparar.html', context)


@login_required
def mis_listas(request):
    listas = Prodxlista.objects.all()
    # productos = Producto.objects.all()

    return render(request, 'bootstrap3/mis_listas.html', {'listas': listas})


def error(request):
    return render(request, 'bootstrap3/404_error.html', {})


def acerca_nosotros(request):
    return render(request, 'bootstrap3/acerca_nosotros.html', {})


def contacto(request):
    return render(request, 'bootstrap3/contacto.html', {})

SuperDealzApp/templates/bootstrap3/404_error.html
{% extends 'bootstrap3/base_user.html' %}
{% block content %}
<div id="content">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col col-lg-8">
        <div class="error-template text-center"> <i class="fa fa-exclamation-triangle fa-5x text-danger animated zoomIn mb50"></i>
          <h3 class="main-title"><span>Oops! 404 Not Found</span></h3>
          <div class="main-title-description"> Sorry, an error has occured, Requested page not found! </div>
          <div class="error-actions"> <a href="index.html" class="btn btn-primary btn-lg">Take Me Home </a> <a href="contacto.html" class="btn btn-light btn-lg">Contact Support </a> </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

SuperDealzApp/templates/bootstrap3/base_inicio.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>SuperDealz</title>

<!-- Bootstrap -->
<link href="https://fonts.googleapis.com/css?family=Libre+Franklin:100,200,300,400,500,700" rel="stylesheet" />
<link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate.css' %}" rel="stylesheet">
<link href="{% static 'lib/selectric/selectric.css' %}" rel="stylesheet">
<link href="{% static 'lib/swiper/css/swiper.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/aos/aos.css' %}" rel="stylesheet">
<link href="{% static 'lib/Magnific-Popup/magnific-popup.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'lib/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'lib/popper.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'lib/selectric/jquery.selectric.js' %}"></script>
<script src="{% static 'lib/swiper/js/swiper.min.js' %}"></script>
<script src="{% static 'lib/aos/aos.js' %}"></script>
<script src="{% static 'lib/Magnific-Popup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'lib/sticky-sidebar/ResizeSensor.min.js' %}"></script>
<script src="{% static 'lib/sticky-sidebar/theia-sticky-sidebar.min.js' %}"></script>
<script src="{% static 'lib/lib.js' %}"></script>

</head>
<body>
<div id="main">

<nav class="navbar navbar-expand-lg navbar-dark navbar-over absolute-top" id="menu">
  <div class="container">
  <a class="navbar-brand" href="/"><span class="icon-uilove-realestate"></span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu-content" aria-controls="menu-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="menu-content">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link dropdown" href="/" aria-haspopup="true" aria-expanded="false">
          Inicio <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown" href="/productos" aria-haspopup="true" aria-expanded="false">
          Productos
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown" href="/acerca_nosotros" aria-haspopup="true" aria-expanded="false">
          Nosotros
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown" href="/contacto" aria-haspopup="true" aria-expanded="false">
          Contacto
        </a>
      </li>
    </ul>

    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown user-account">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="user-image" style="background-image:url({% static 'img/demo/profile2.jpg' %});"></span> {{ user.username|capfirst }}
        </a>
        <div class="dropdown-menu">
          <a href="/mi-perfil" class="dropdown-item">Mi Perfil</a>
          <a href="/mis-listas" class="dropdown-item">Mis Listas</a>
          <a href="{% url 'superdealz:logout' %}" class="dropdown-item"> Cerrar Sesion</a>
        </div>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="{% url 'superdealz:login' %}" class="nav-link dropdown">Iniciar Sesion</a>
      </li>
      <li class="nav-item">
        <a href="/registro" class="nav-link dropdown">Registrarse</a>
      </li>
    </ul>
    {% endif %}

  </div>
  </div>
</nav>
<div class="home-search">
<div class="main search-form v2">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-12 col-lg-10">
        <div class="heading">
          <h2>COMPARANDO ELEGIMOS MEJOR</h2>
          <h3>Buscar Productos</h3>
        </div>
        <form type="get" action="{% url "superdealz:productos" %}">
          <div class="row justify-content-md-center">
            <div class="col-md-9 col-lg-8">
              <div class="input-group input-group-lg">
                <input type="text" class="form-control" placeholder="Buscar por Marca, Nombre, Categoria." name="q" value="{{ query }}">
                <span class="input-group-append">
                <button type="submit" class="btn btn-primary btn-lg" >Buscar!</button>
                </span>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
    {% block content %}
    {% endblock %}

<button class="btn btn-primary btn-circle" id="to-top"><i class="fa fa-angle-up"></i></button>
<footer id="footer" class="bg-light footer-light">
<div class="container container-1000">
<div class="row">
<div class="col-lg-3">
<p><span class="icon-uilove icon-uilove-realestate"></span></p>
<address class="mb-3">
            <strong>Viña del Mar, Chile</strong><br>
            <abbr title="Phone">T:</abbr> +56973819041
            </address>
<div class="footer-social mb-4"><a href="#" class="ml-2 mr-2"><span class="fa fa-twitter"></span></a> <a href="#" class="ml-2 mr-2"><span class="fa fa-facebook"></span></a> <a href="#" class="ml-2 mr-2"><span class="fa fa-instagram"></span></a></div>
</div>
<div class="col-lg-2 col-sm-4">
<div class="footer-links">
<ul class="list-unstyled">
<li class="list-title"><a href="#">NOSOTROS</a></li>
<li><a href="/acerca_nosotros">Nosotros</a></li>
<li><a href="#">Terminos y Condiciones</a></li>
<li><a href="/contacto">Contacto</a></li>
</ul>
</div>
</div>
<div class="col-lg-2 col-sm-4">
<div class="footer-links">
<ul class="list-unstyled">
<li class="list-title"><a href="#">LINKS</a></li>
<li><a href="/productos">Productos</a></li>
<li><a href="#">Mi lista</a></li>
</ul>
</div>
</div>
<div class="col-lg-2 col-sm-4">
<div class="footer-links">
<ul class="list-unstyled">
<li class="list-title"><a href="#">AYUDA</a></li>
<li><a href="#">FAQ</a></li>
</ul>
</div>
</div>
<div class="col-lg-3">
<div class="text-lg-right ml-lg-2">
<form>
<div class="list-title">Suscribete</div>
<div class="input-group input-group-lg">
  <input type="text" name="email" class="form-control form-control-lg subscribe-input" placeholder="Email">
<div class="input-group-append ml-0">
    <button class="btn subscribe-button" type="button"><i class="fa fa-envelope"></i></button>
  </div>
</div>
</form>
</div>
</div>

</div>
<div class="footer-credits d-lg-flex justify-content-lg-between align-items-center">

<div>© 2018 SuperDealz. All Rights Reserved</div>
</div>
</div>
</footer>
</div>
</body>
</html>

SuperDealzApp/templates/bootstrap3/base_user.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>SuperDealz</title>

<!-- Bootstrap -->
<link href="https://fonts.googleapis.com/css?family=Libre+Franklin:100,200,300,400,500,700" rel="stylesheet" />
<link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate.css' %}" rel="stylesheet">
<link href="{% static 'lib/selectric/selectric.css' %}" rel="stylesheet">
<link href="{% static 'lib/swiper/css/swiper.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/aos/aos.css' %}" rel="stylesheet">
<link href="{% static 'lib/Magnific-Popup/magnific-popup.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'lib/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'lib/popper.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'lib/selectric/jquery.selectric.js' %}"></script>
<script src="{% static 'lib/swiper/js/swiper.min.js' %}"></script>
<script src="{% static 'lib/aos/aos.js' %}"></script>
<script src="{% static 'lib/Magnific-Popup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'lib/sticky-sidebar/ResizeSensor.min.js' %}"></script>
<script src="{% static 'lib/sticky-sidebar/theia-sticky-sidebar.min.js' %}"></script>
<script src="{% static 'lib/lib.js' %}"></script>


</head>
<body>
<div id="main">

<nav class="navbar navbar-expand-lg navbar-dark" id="menu">
  <div class="container">
  <a class="navbar-brand" href="/"><span class="icon-uilove icon-uilove-realestate"></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu-content" aria-controls="menu-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="menu-content">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link dropdown" href="/" role="button" aria-haspopup="true" aria-expanded="false">
          Inicio <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown" href="/productos" role="button" aria-haspopup="true" aria-expanded="false">
          Productos 
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown" href="/acerca_nosotros" aria-haspopup="true" aria-expanded="false">
          Nosotros 
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown" href="/contacto" aria-haspopup="true" aria-expanded="false">
          Contacto 
        </a>
      </li>
    </ul>

    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown user-account">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="user-image" style="background-image:url({% static 'img/demo/profile3.jpg' %});"></span> {{ user.username|capfirst }}
        </a>
        <div class="dropdown-menu">
          <a href="/mi-perfil" class="dropdown-item">Mi Perfil</a>
          <a href="/mis-listas" class="dropdown-item">Mis Listas</a>
          <a href="{% url 'superdealz:logout' %}" class="dropdown-item"> Cerrar Sesion</a>
        </div>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="{% url 'superdealz:login' %}" class="nav-link dropdown">Iniciar Sesion</a>
      </li>
      <li class="nav-item">
        <a href="/registro" class="nav-link dropdown">Registrarse</a>
      </li>
    </ul>
    {% endif %}
   
  </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<button class="btn btn-primary btn-circle" id="to-top"><i class="fa fa-angle-up"></i></button>
<footer id="footer" class="bg-light footer-light">
<div class="container container-1000">
<div class="row">
<div class="col-lg-3">
<p><span class="icon-uilove icon-uilove-realestate"></span></p>
<address class="mb-3">
            <strong>Viña del Mar, Chile</strong><br>
            <abbr title="Phone">T:</abbr> +56973819041
            </address>
<div class="footer-social mb-4"><a href="#" class="ml-2 mr-2"><span class="fa fa-twitter"></span></a> <a href="#" class="ml-2 mr-2"><span class="fa fa-facebook"></span></a> <a href="#" class="ml-2 mr-2"><span class="fa fa-instagram"></span></a></div>
</div>
<div class="col-lg-2 col-sm-4">
<div class="footer-links">
<ul class="list-unstyled">
<li class="list-title"><a href="#">NOSOTROS</a></li>
<li><a href="/acerca_nosotros">Nosotros</a></li>
<li><a href="#">Terminos y Condiciones</a></li>
<li><a href="/contacto">Contacto</a></li>
</ul>
</div>
</div>
<div class="col-lg-2 col-sm-4">
<div class="footer-links">
<ul class="list-unstyled">
<li class="list-title"><a href="#">LINKS</a></li>
<li><a href="/productos">Productos</a></li>
<li><a href="#">Mi lista</a></li>
</ul>
</div>
</div>
<div class="col-lg-2 col-sm-4">
<div class="footer-links">
<ul class="list-unstyled">
<li class="list-title"><a href="#">AYUDA</a></li>
<li><a href="#">FAQ</a></li>
</ul>
</div>
</div>
<div class="col-lg-3">
<div class="text-lg-right ml-lg-2">
<form>
<div class="list-title">Suscribete</div>
<div class="input-group input-group-lg">
  <input type="text" name="email" class="form-control form-control-lg subscribe-input" placeholder="Email">
<div class="input-group-append ml-0">
    <button class="btn subscribe-button" type="button"><i class="fa fa-envelope"></i></button>
  </div>
</div>
</form>
</div>
</div>

</div>
<div class="footer-credits d-lg-flex justify-content-lg-between align-items-center">

<div>© 2018 SuperDealz. All Rights Reserved</div>
</div>
</div>
</footer>
</div>
</body>
</html>