SuperDealzWeb/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('superdealzapp.urls', namespace='superdealz')),
    path('admin/', admin.site.urls),
    path('bootstrap3/',
         TemplateView.as_view(template_name='bootstrap3/inicio.html')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<id_producto>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<id_producto>\d+)/$', views.cart_remove, name='cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    cantidad = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    actualizar = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from superdealzapp.models import Producto
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, id_producto):
    cart = Cart(request)
    producto = get_object_or_404(Producto, id=id_producto)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(producto=producto, cantidad=cd['cantidad'], actualizar_cantidad=cd['actualizar'])
    return redirect('cart:cart_detail')


def cart_remove(request, id_producto):
    cart = Cart(request)
    producto = get_object_or_404(Producto, id=id_producto)
    cart.remove(producto)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'cantidad': item['cantidad'], 'actualizar': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/detail.html
{% extends 'superdealzapp/base_user.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with producto=item.producto  %}
                        <tr>
                            <td>
                                <a href="{{ producto.get__absolute_url }}">
                                    <img src="{% if producto.imagen %} {{ producto.imagen }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ producto.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" producto.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.cantidad }}
                                    {{ item.update_quantity_form.actualizar }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" producto.id %}">Remove</a>
                            </td>
                            <td>kshs. {{ item.price }}</td>
                            <td>kshs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}